services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade-bot01
    restart: unless-stopped
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade --config /freqtrade/user_data/config_price-act_strategy.json
            --strategy PriceActionStrategy
            --dry-run
    environment:
      - FREQTRADE__API_SERVER__ENABLED=true
      - FREQTRADE__API_SERVER__LISTEN_IP_ADDRESS=0.0.0.0
      - FREQTRADE__API_SERVER__LISTEN_PORT=8080
      # Pairlist now configured in JSON only to avoid env merge conflicts
      # Proxy settings (configured via .env file)
      - HTTP_PROXY=${PROXY_URL}
      - HTTPS_PROXY=${PROXY_URL}
      - NO_PROXY=localhost,127.0.0.1
    ports:
      - "6677:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freqtrade.rule=Host(`localhost`)"
      - "traefik.http.routers.freqtrade.entrypoints=websecure"
      - "traefik.http.routers.freqtrade.tls.certresolver=letsencrypt"
      - "traefik.http.services.freqtrade.loadbalancer.server.port=8080"
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true