# 单独部署 Freqtrade
# 使用方法: docker-compose -f docker-compose.freqtrade.yml up -d

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade-bot01
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade --config /freqtrade/user_data/config_classic_strategy.json
            --strategy ClassicStrategy
            --dry-run
    environment:
      - FREQTRADE__API_SERVER__ENABLED=true
      - FREQTRADE__API_SERVER__LISTEN_IP_ADDRESS=0.0.0.0
      - FREQTRADE__API_SERVER__LISTEN_PORT=8080
      # Proxy settings (configured via .env file)
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - NO_PROXY=localhost,127.0.0.1
    # ports not needed with host network mode
    # ports:
    #   - "6677:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freqtrade.rule=Host(`localhost`)"
      - "traefik.http.routers.freqtrade.entrypoints=websecure"
      - "traefik.http.routers.freqtrade.tls.certresolver=letsencrypt"
      - "traefik.http.services.freqtrade.loadbalancer.server.port=8080"
    # networks not compatible with host mode
    # networks:
    #   - traefik
    #   - default

networks:
  traefik:
    external: true