[project]
name = "freqtrade-classic-strategy"
version = "0.1.0"
description = "Docker Freqtrade classic candlestick pattern strategy"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [

]